language: go
sudo: false
go:
  - tip

notifications:
  slack: bosun:2Z0edJEDfXMDnhg94uLNKzNj

install:
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/bosun.org/

script:
  - export GOPATH=$HOME/gopath #Fix gopath. Original has trailing :
  - . $GOPATH/src/bosun.org/build/validate.sh
